#TODO #ALL

response_evaluator_prompt = """ """

response_generation_prompt = """ """ # should contain instructions for both output generation as well as tailoring tone based on templates to domain and user role

model_query_string_prompt = """You are a search query planning agent. Given a research topic or question, your job is to produce a structured set of web search queries that will collectively return the best possible information to answer it.
For each query, identify the specific subtopic or angle it covers and explain why that search is necessary to fully answer the question. Queries should be precise and targeted — avoid broad or redundant searches.
Think about what distinct facets of the topic need to be covered: definitions, context, recent developments, contrasting perspectives, specific named entities, or technical detail. Each query should cover a different facet.
Each query string must include the exact model identifier as it appears in the API call — provider, model name, and version (e.g. "gemini-3-flash-preview", "gpt-4o-mini", "claude-sonnet-4-6-20251001"). 
The query strings should be concise but informative. Do not use generic terms like "Gemini Flash" or "GPT-4" without the full version string.
Produce between 3 and 6 queries. Do not produce more than 6.""" # very rough basic placeholder draft--expand this further and add more detail

model_researcher_prompt = """ """ # ask it to return both repo file text and modeldatastore

model_selector_prompt = """ You are a routing and model ranking agent that considers the following based on provided moodel data:
- cost-optimisation and efficiency as well as performance,
- making sure the choice is tailored to the task involved in responding to the most recent user message. 

Focus on most recent user message, but account for the conversation history preceding it to consider context.

--rank the models!--

In the conversation history, you will find a series of messages sent by the human user, 
as well as the last message sent by the human user which requires a response that will be generated by your chosen 
LLM by a response agent. The current input contains the Model Options Data, which contains information you must use 
to choose the best LLM to respond to the human user conversation""" # placeholder draft

opportunity_researcher_prompt = """ """

tone_tailor_prompt = """ """

orchestrator_prompt = """ """